### ISSUE TITLE
JSON for reading printer status

### ISSUE THREAD

**Issue by BerranRemzi** [xreef/beeprint_3d_printer_web_interface#2]
It will helpful to add functionality for reading printer status by simple JSON:
- File name
- File size
- Elapsed time
- Remaining time

I know this will cost you time, so my question is "Is there an easy way to read these parameters with get request (another ESP)"?

**Comment by xreef** [comment]
Hi,
yes you can subscribe the websocket and read the message with that information.
you can find the needed information here
https://mischianti.org/it/mks-wifi-per-makerbase-robin-aggiornamento-del-firmware-e-nuova-funzionalita-web-socket-4/#Test_WebSocket
Bye Renzo
